#include "ants_sim/movement_tables.hpp"

// Generated by tools/extract_movement_tables.py (do not edit by hand).
#include "movement_tables_data.inc"

#include <algorithm>
#include <iterator>

namespace ants::sim::movement {

namespace {

// Stored source direction of every direction: 5 SW, 6 W and 7 NW mirror 3 SE, 2 E and 1 NE.
constexpr uint8_t kSourceDir[kDirectionCount] = {0, 1, 2, 3, 4, 3, 2, 1};

constexpr std::size_t kClipCount = std::size(data::kClips);

// Position of a CHD index in kClips (sorted), or kClipCount.
constexpr std::size_t find_clip(uint16_t chd_index) noexcept {
    std::size_t lo = 0;
    std::size_t hi = kClipCount;
    while (lo < hi) {
        const std::size_t mid = lo + (hi - lo) / 2;
        if (data::kClips[mid].chd_index < chd_index) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    return (lo < kClipCount && data::kClips[lo].chd_index == chd_index) ? lo : kClipCount;
}

// ---- compile-time consistency of the generated data ------------------------------------------
constexpr bool clips_sorted_and_contiguous() noexcept {
    std::size_t next_frame = 0;
    for (std::size_t i = 0; i < kClipCount; ++i) {
        const data::ClipRec& c = data::kClips[i];
        if (i > 0 && data::kClips[i - 1].chd_index >= c.chd_index) return false;
        if (c.chd_index >= kTileIdCount || c.frame_count == 0 || c.first_frame != next_frame) return false;
        next_frame += c.frame_count;
    }
    return next_frame == std::size(data::kFrames);
}

constexpr bool present_or_none(uint16_t chd_index) noexcept {
    return chd_index == kNoAnimation || find_clip(chd_index) < kClipCount;
}

constexpr bool all_referenced_clips_present() noexcept {
    for (uint8_t t = 0; t < kAntTypeCount; ++t) {
        for (uint8_t tr = 0; tr < kTerrainClassCount; ++tr) {
            for (uint8_t d = 0; d < 5; ++d) {
                const bool water = tr == kTerrainWater;
                if (water != (data::kWalk[t][tr][d] == kNoAnimation)) return false;
                if (water != (data::kCarryWalk[t][tr][d] == kNoAnimation)) return false;
                if (!present_or_none(data::kWalk[t][tr][d]) || !present_or_none(data::kCarryWalk[t][tr][d])) {
                    return false;
                }
            }
        }
        for (uint8_t d = 0; d < 5; ++d) {
            if (find_clip(data::kIdle[t][d]) == kClipCount || find_clip(data::kCarryIdle[t][d]) == kClipCount) {
                return false;
            }
        }
        if (find_clip(data::kCantGo[t]) == kClipCount || find_clip(data::kCarryCantGo[t]) == kClipCount) {
            return false;
        }
    }
    for (uint8_t d = 0; d < 5; ++d) {
        if (find_clip(data::kSwim[d]) == kClipCount || find_clip(data::kDive[d]) == kClipCount ||
            find_clip(data::kClimb[d]) == kClipCount) {
            return false;
        }
    }
    return find_clip(data::kIdleWater) < kClipCount && find_clip(data::kBump) < kClipCount;
}

static_assert(std::size(data::kTileTerrain) == kTileIdCount, "one terrain class per CHD tile id");
static_assert(std::size(data::kTileFlags) == kTileIdCount, "one flag byte per CHD tile id");
static_assert(std::size(data::kPassableByTerrain) == 8 && std::size(data::kStepWeight) == 6,
              "terrain table sizes as in Ants.exe");
static_assert(std::size(data::kDirTable) == 9 && std::size(data::kNeighbour) == kDirectionCount,
              "direction table sizes as in Ants.exe");
static_assert(clips_sorted_and_contiguous(), "kClips must be sorted by CHD index and tile kFrames exactly");
static_assert(all_referenced_clips_present(), "every table entry must have its clip in kClips");

MotionClip make_clip(std::size_t pos, bool mirrored) noexcept {
    if (pos >= kClipCount) return {};
    const data::ClipRec& c = data::kClips[pos];
    MotionClip clip;
    clip.frames = &data::kFrames[c.first_frame];
    clip.count = c.frame_count;
    clip.chd_index = c.chd_index;
    clip.mirrored = mirrored;
    clip.flags = c.flags;
    return clip;
}

// Directional lookup into a stored row of directions 0..4.
MotionClip directional(const uint16_t (&row)[5], uint8_t dir) noexcept {
    if (dir >= kDirectionCount) return {};
    return clip_by_chd(row[kSourceDir[dir]], dir > 4);
}

}  // namespace

// ---- MotionClip ---------------------------------------------------------------------------------
int16_t MotionClip::dx(uint16_t i) const noexcept {
    if (frames == nullptr || i >= count) return 0;
    const int16_t v = frames[i].dx;
    return mirrored ? static_cast<int16_t>(-v) : v;
}

int16_t MotionClip::dy(uint16_t i) const noexcept {
    return (frames == nullptr || i >= count) ? int16_t{0} : frames[i].dy;
}

uint16_t MotionClip::duration(uint16_t i) const noexcept {
    return (frames == nullptr || i >= count) ? uint16_t{0} : frames[i].duration_ms;
}

uint16_t MotionClip::event(uint16_t i) const noexcept {
    return (frames == nullptr || i >= count) ? uint16_t{0} : frames[i].event;
}

int16_t MotionClip::sound(uint16_t i) const noexcept {
    return (frames == nullptr || i >= count) ? kSoundNone : frames[i].sound;
}

uint32_t MotionClip::total_duration_ms() const noexcept {
    uint32_t total = 0;
    for (uint16_t i = 0; frames != nullptr && i < count; ++i) total += frames[i].duration_ms;
    return total;
}

// ---- clip lookup --------------------------------------------------------------------------------
MotionClip clip_by_chd(uint16_t chd_index, bool mirrored) noexcept {
    return make_clip(find_clip(chd_index), mirrored);
}

MotionClip walk_clip(uint8_t ant_type, uint8_t terrain_class, uint8_t dir, bool carrying) noexcept {
    if (ant_type >= kAntTypeCount || terrain_class >= kTerrainClassCount) return {};
    const auto& table = carrying ? data::kCarryWalk : data::kWalk;
    return directional(table[ant_type][terrain_class], dir);
}

MotionClip swim_clip(uint8_t dir) noexcept { return directional(data::kSwim, dir); }
MotionClip dive_clip(uint8_t dir) noexcept { return directional(data::kDive, dir); }
MotionClip climb_clip(uint8_t dir) noexcept { return directional(data::kClimb, dir); }

MotionClip idle_clip(uint8_t ant_type, uint8_t dir, bool carrying) noexcept {
    if (ant_type >= kAntTypeCount) return {};
    const auto& table = carrying ? data::kCarryIdle : data::kIdle;
    return directional(table[ant_type], dir);
}

MotionClip idle_water_clip() noexcept { return clip_by_chd(data::kIdleWater); }

MotionClip cant_go_clip(uint8_t ant_type, bool carrying) noexcept {
    if (ant_type >= kAntTypeCount) return {};
    return clip_by_chd(carrying ? data::kCarryCantGo[ant_type] : data::kCantGo[ant_type]);
}

MotionClip bump_clip() noexcept { return clip_by_chd(data::kBump); }

std::size_t clip_count() noexcept { return kClipCount; }

MotionClip clip_at(std::size_t i) noexcept { return make_clip(i, false); }

// ---- tiles and terrain --------------------------------------------------------------------------
uint8_t terrain_class_of_tile(uint16_t tile_id) noexcept {
    return tile_id < kTileIdCount ? data::kTileTerrain[tile_id] : uint8_t{kTerrainGrass};
}

uint8_t terrain_class_of_cell(uint16_t layer1_tile_id, uint16_t layer2_tile_id) noexcept {
    return is_bridge_tile(layer2_tile_id) ? uint8_t{kTerrainMud} : terrain_class_of_tile(layer1_tile_id);
}

uint8_t tile_flags_of(uint16_t tile_id) noexcept {
    return tile_id < kTileIdCount ? data::kTileFlags[tile_id] : uint8_t{0};
}

bool is_bridge_tile(uint16_t tile_id) noexcept {
    return std::find(std::begin(data::kBridgeTiles), std::end(data::kBridgeTiles), tile_id) !=
           std::end(data::kBridgeTiles);
}

bool terrain_walkable(uint8_t terrain_class) noexcept {
    return static_cast<std::size_t>(terrain_class) < std::size(data::kPassableByTerrain) &&
           data::kPassableByTerrain[terrain_class] != 0;
}

uint32_t terrain_step_weight(uint8_t terrain_class, bool swimmer) noexcept {
    if (swimmer && terrain_class == kTerrainWater) return data::kSwimmerWaterWeight;
    if (static_cast<std::size_t>(terrain_class) >= std::size(data::kStepWeight)) {
        return data::kStepWeight[kTerrainWater];
    }
    return data::kStepWeight[terrain_class];
}

// ---- directions ---------------------------------------------------------------------------------
int dir_from_delta(int drow, int dcol) noexcept {
    const int r = (drow > 0) - (drow < 0);
    const int c = (dcol > 0) - (dcol < 0);
    return data::kDirTable[(r + 1) * 3 + (c + 1)];
}

TileDelta dir_delta(uint8_t dir) noexcept {
    if (dir >= kDirectionCount) return {};
    return TileDelta{data::kNeighbour[dir][0], data::kNeighbour[dir][1]};
}

}  // namespace ants::sim::movement
