services:
  ants-web:
    image: ants-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ants-web
    restart: unless-stopped
    ports:
      - "${ANTS_PORT:-8080}:80"
    environment:
      - VIRTUAL_HOST=beta.playants.org
      - LETSENCRYPT_HOST=beta.playants.org
