services:
  ants-beta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ants-beta
    restart: unless-stopped
    ports:
      - "${ANTS_PORT:-19980}:80"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
