services:
  ants-beta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ants-beta
    restart: unless-stopped
    ports:
      - "${ANTS_PORT:-19980}:80"
    environment:
      - VIRTUAL_HOST=beta.playants.org
      - LETSENCRYPT_HOST=beta.playants.org
