// Writes src/ants_sim/food_footprints_data.inc: the cells every food tile occupies relative to its anchor tile, computed from
// Original-Ants/ants.chd the way Ants.exe places objects (see include/ants_assets/object_footprint.hpp). The output is
// deterministic. Usage:
//   cmake --build build --target gen_food_footprints
//   ./build/gen_food_footprints > src/ants_sim/food_footprints_data.inc
// tests/test_assets/test_movement_tables.cpp recomputes the table and fails when the committed file is stale.
#include <cstdio>
#include <string>
#include <vector>

#include "ants_assets/asset_archive.hpp"
#include "ants_assets/object_footprint.hpp"
#include "ants_sim/movement_tables.hpp"

#ifndef ORIGINAL_ASSETS_DIR
#define ORIGINAL_ASSETS_DIR "Original-Ants"
#endif

int main() {
    ants::assets::AssetArchive archive;
    if (!archive.load_chd(std::string(ORIGINAL_ASSETS_DIR) + "/ants.chd")) {
        std::fprintf(stderr, "cannot load ants.chd\n");
        return 1;
    }
    struct Entry {
        uint32_t tile;
        std::vector<ants::assets::FootprintOffset> cells;
    };
    std::vector<Entry> entries;
    size_t total = 0;
    for (uint32_t tile = 0; tile < ants::sim::movement::kTileIdCount; ++tile) {
        if ((ants::sim::movement::tile_flags_of(static_cast<uint16_t>(tile)) & ants::sim::movement::kTileFlagFood) == 0) continue;
        Entry e{tile, ants::assets::compute_object_footprint(archive, tile)};
        total += e.cells.size();
        entries.push_back(std::move(e));
    }
    std::printf("// Generated by tools/gen_food_footprints.cpp from Original-Ants/ants.chd - do not edit.\n");
    std::printf("// Cells (columns, rows from the anchor tile) that a food tile occupies when it is placed on the map (Ants.exe\n");
    std::printf("// FUN_01007a22 / FUN_0100744f / FUN_01007710: the first frame's box cut with the first part's image, a tile belongs\n");
    std::printf("// to the object when it holds a pixel that is not the colour key).\n");
    std::printf("#ifndef ANTS_SIM_FOOD_FOOTPRINTS_DATA_INC\n#define ANTS_SIM_FOOD_FOOTPRINTS_DATA_INC\n\n");
    std::printf("namespace ants::sim::movement::data {\n\n");
    std::printf("struct FoodFootprint {\n    uint16_t tile;\n    uint16_t first;   // index into kFootprintCells\n    uint16_t count;\n};\n\n");
    std::printf("inline constexpr FootprintCell kFootprintCells[%zu] = {  // ants::sim::movement::FootprintCell\n", total);
    for (const Entry& e : entries) {
        std::printf("    // tile %u %s\n   ", e.tile, archive.get_animation(e.tile).name.c_str());
        for (const auto& c : e.cells) std::printf(" {%d, %d},", c.dcol, c.drow);
        std::printf("\n");
    }
    std::printf("};\n\n");
    std::printf("inline constexpr FoodFootprint kFoodFootprints[%zu] = {\n", entries.size());
    uint32_t first = 0;
    for (const Entry& e : entries) {
        std::printf("    {%u, %u, %zu},  // %s\n", e.tile, first, e.cells.size(), archive.get_animation(e.tile).name.c_str());
        first += static_cast<uint32_t>(e.cells.size());
    }
    std::printf("};\n\n");
    std::printf("}  // namespace ants::sim::movement::data\n\n#endif  // ANTS_SIM_FOOD_FOOTPRINTS_DATA_INC\n");
    return 0;
}
