# Writes the one translation unit that holds ants::BUILD_ID (ants_app/version.hpp.in). Run by the build (not only by the configure step) through
#   cmake -DSOURCE_DIR=... -DOUT_FILE=... [-DGIT_EXECUTABLE=...] [-DANTS_BUILD_ID=...] -P ants_stamp_build_id.cmake
# so that a new commit shows in the next build without a new configure; the file is rewritten only when its content changes (a build after no commit
# recompiles nothing).
#
# The id: an explicit ANTS_BUILD_ID (the Docker images pass one) wins; else the short git commit when SOURCE_DIR is a git checkout and git works (no
# "-dirty" suffix: the id names a commit, not the state of a working tree); else "unknown".

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "ants_stamp_build_id.cmake needs -DSOURCE_DIR=... and -DOUT_FILE=...")
endif()

set(build_id "")
if(ANTS_BUILD_ID)
    set(build_id "${ANTS_BUILD_ID}")
elseif(GIT_EXECUTABLE AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short HEAD
        RESULT_VARIABLE git_status
        OUTPUT_VARIABLE git_out
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(git_status EQUAL 0)
        set(build_id "${git_out}")
    endif()
endif()

# The id ends up inside a C++ string literal and on web pages: letters, digits, dot, dash and underscore only, at most 40 characters.
string(LENGTH "${build_id}" build_id_length)
if(build_id STREQUAL "" OR build_id_length GREATER 40 OR NOT build_id MATCHES "^[A-Za-z0-9._-]+$")
    set(build_id "unknown")
endif()

set(content "// Generated by cmake/ants_stamp_build_id.cmake at every build; do not edit. See ants_app/version.hpp.in.\n#include \"ants_app/version.hpp\"\n\nnamespace ants {\nconst std::string_view BUILD_ID = \"${build_id}\";\n}  // namespace ants\n")

set(old_content "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" old_content)
endif()
if(NOT old_content STREQUAL content)
    get_filename_component(out_dir "${OUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${out_dir}")
    file(WRITE "${OUT_FILE}" "${content}")
endif()
